### ISSUE TITLE
Fix compatibility with Erlang/OTP 18

### ISSUE THREAD

**Issue by ferigis** [cabol/erlbus#17]
I am using Erlang/OTP 18. When I try to make from /erlbus folder I get this error:
...
andler.erl ebus_dist_ring_event_handler.erl ebus_global_sup.erl ebus_gproc.erl ebus_handler.erl ebus_pg2.erl ebus_sup.erl ebus_util.erl ebus_worker.erl
compile: warnings being treated as errors
src/ebus_dist.erl:139: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
make[1]: **\* [ebin/ebus.app] Error 1
make: **\* [all] Error 2
...

but it works fine if I build an app with erlbus as a dependence.

**Comment by cabol** [comment]
Fixed
