### ISSUE TITLE
erlang:get_stacktrace() stop working on v21

### ISSUE THREAD

**Issue by jochasinga** [cabol/erlbus#40]
The use of `erlang:get_stacktrace()` in here https://github.com/cabol/erlbus/blob/a3e412b658df3ff876d71319702daa96140a789a/src/utils/ebus_task.erl#L266-L273 is failing. Should be modified to use this syntax:

```erlang
try
    apply(Module, Fun, Args)
  catch
    _Class:Reason:_Stacktrace ->
      exit(Info, MFA, Reason, Reason);
   % ...
  end.
```

**Comment by cabol** [comment]
@jochasinga it is fixed now – I'm aiming to publish today a "version bump" with these changes
