### ISSUE TITLE
Compatibility with OTP 24

### ISSUE THREAD

**Issue by ssantaaa47** [cabol/erlbus#41]
I am not able to compile erlbus with OTP 24 since PG2 module is deprecated in OTP 23 and removed in OTP 24 and replaced with PG module...

**Comment by cabol** [comment]
Yeah, it is necessary to provide an abstraction for `pg2` and `pg` modules and use them depending on the OTP version. I will check it out and try to push a fix soon. Thanks!!

**Comment by cabol** [comment]
Fixed!
